### ISSUE TITLE
The orcs are not spawning in the right area

### ISSUE THREAD

**Issue by ProfElements** [rhymu8354/OmniaRegna#193]
As seen below, the orcs (the ones with the clubs don't seem to be spawning in the right area.
Please close this issue if It is a misunderstanding of spawning mechanics

![image](https://user-images.githubusercontent.com/43350117/62588893-fd882100-b88c-11e9-8904-6d37ecc9c1e0.png)

**Comment by rhymu8354** [comment]
I found out this is because the orcs are spawning and then randomly wandering into the area at the lower-right there, and then getting stuck because they've pulled aggro on players who have teleported back to town at X/Y coordinates near them but different zone ID.

I'd like to fix this by two changes:

1. Move spawn point a little bit down and reduce wander range to keep them in one area.
2. Fix the aggro system so that players that move to a different zone are dropped from the aggro table.

**Comment by rhymu8354** [comment]
Now that I've deployed updates that allow the NPCs to search and path-find properly, I believe this issue is fixed.  The orcs should no longer get stuck in corners and be unable to return to their own area.
